# Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.network "private_network", ip: "192.168.56.10"

  # 安裝 Docker
  config.vm.provision "shell", path: "install-docker.sh"

  # 安裝 Kafka
  config.vm.provision "shell", path: "install-kafka.sh", privileged: false
end
